"""
MCP Run Test Script
Executes a predefined action plan on the Sauce Demo website using the MCPExecutor.
"""

from mcp_agent import MCPExecutor
from playwright.sync_api import sync_playwright

# Example plan generated by the AI (via MCP):
plan = [
    {"action": "read_text", "selector": ".inventory_item_name", "index": 5}
]

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False, slow_mo=500) # launch browser
    page = browser.new_page() # open a new page

    executor = MCPExecutor(page) # create MCPExecutor instance
    executor.auto_login_sauce()  # login first

    valid, msg = executor.validate_plan(plan) # validate the plan
    print("Validation:", valid, msg)

    results = executor.execute_plan(plan) # execute the plan
    print("Execution results:", results)

    browser.close()
